# 应用名称(集群下相同)
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          # 是否与服务发现组件进行结合，通过serviceId 转发到具体服务实例。
          enabled: true                # 是否开启基于服务发现的路由规则
          lower-case-service-id: true  # 是否将服务名称转小写
      #路有规则
      routes:
        - id: service-provider         # 路由ID，唯一
          uri: http://localhost:6061/  # 目标URI，路由到微服务的地址
          predicates:
            - Path=/product/**
          filters:                     # 网关过滤器
            - name: RequestRateLimiter # 限流过滤器
              args:
                redis-rate-limiter.replenishRate: 1 # 令牌桶每秒填充速率
                redis-rate-limiter.burstCapacity: 2 # 令牌桶总容量
                key-resolver: "#{@pathKeyResolver}" # 使用SpEL 表达式按名称引用
  # redis 缓存
  redis:
    timeout: 10000          # 连接超时时间
    host: 172.17.210.104    # Redis服务器地址
    port: 6379              # Redis服务器端口
    database: 0             # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024    # 最大连接数，默认8
        max-wait: 10000     # 最大连接阻塞等待时间，单位毫秒，默认-1
        max-idle: 200       # 最大空闲连接，默认8
        min-idle: 5         # 最小空闲连接，默认0
# 端口
server:
  port: 9200
# 配置Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true # 是否使用ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/


