# 应用名称
spring:
  application:
    name: service-consumer
  # redis 缓存
  redis:
    timeout: 10000          # 连接超时时间
    host: 172.18.63.178    # Redis服务器地址
    port: 6379              # Redis服务器端口
    database: 0             # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024    # 最大连接数，默认8
        max-wait: 10000     # 最大连接阻塞等待时间，单位毫秒，默认-1
        max-idle: 200       # 最大空闲连接，默认8
        min-idle: 5         # 最小空闲连接，默认0

# 端口
server:
  port: 7071
  tomcat:
    max-threads: 10      # 降低最大线程数方便模拟高并发
# 配置Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true # 是否使用ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    register-with-eureka: true         # 是否将自己注册到注册中心，默认为true
    registry-fetch-interval-seconds: 10 # 表示Eureka Client 间隔多久去服务器拉取注册信息，默认为30 秒
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/
# 度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


