# 应用名称(集群下相同)
spring:
  application:
    name: eureka-server
  #安全认证
  security:
    user:
      name: root
      password: 123456
# 端口
server:
  port: 8761
# 配置Eureka Server 注册中心
eureka:
  instance:
    hostname: eureka01      # 主机名，不配置的时候将根据操作系统的主机名来获取
    prefer-ip-address: true # 是否使用ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@localhost:8762/eureka/

